# Generated by Django 6.0.4 on 2026-05-01 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_drugrequest_requested_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='drugrequest',
            old_name='requested_to',
            new_name='to_user',
        ),
        migrations.RemoveField(
            model_name='drugrequest',
            name='requested_by',
        ),
        migrations.AddField(
            model_name='drugrequest',
            name='from_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drugrequest',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='drugrequest',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
